package datastore

var createItemQuery string = `
	insert into items(
		id integer primary key,
		street text,
		house_number text,
		house_number_add text,
		post_code string
		city text,
		sub_area text,
		estate_owner text,
		min_price text,
		project_name text,
		house_type_in_project text,
		description_nl text,
		description_fr text,
		description_en text,
		description_de text,
		description_es text,
		desctiption_it text,
		brochure_url text,
		plan_url text,
		build_year text,
		furnished numeric,
		hide_price numeric,
		update_photos numeric,
		parking numeric,
		bath numeric,
		separate_shower numeric,
		separate_toilet numeric,
		lift numeric,
		swimming_pool numeric,
		air_conditioning numeric,
		fire_place numeric,
		garage numeric,
		cellar numeric,
		show_house_num numeric,
		photos text,
		tenant integer,
		area integer,
		nr_of_bathrooms integer,
		contract_length integer,
		nr_of_rooms integer,
		nr_of_living_rooms integer,
		stats text,
		available numeric,
		insert_date numeric,
		type text,
		pt_quality text,
		ground_floor text,
		garden numeric,
		garden_loc text,
		garden_area integer,
		roof_terrass numeric,
		roof_terrass_loc text,
		roof_terrass_area integer,
		balcony numeric,
		balcony_loc numeric,
		balcony_area integer,
		floor_quality text,
		rent_included text	
	) 
	values (
		?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
		?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
		?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
		?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
		?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
		?, ?, ?
	)
`
var createItemsTableQuery string = `
	create table if not exists 
	items(
		id integer primary key,
		street text,
		house_number text,
		house_number_add text,
		post_code string
		city text,
		sub_area text,
		estate_owner text,
		min_price text,
		project_name text,
		house_type_in_project text,
		description_nl text,
		description_fr text,
		description_en text,
		description_de text,
		description_es text,
		desctiption_it text,
		brochure_url text,
		plan_url text,
		build_year text,
		furnished numeric,
		hide_price numeric,
		update_photos numeric,
		parking numeric,
		bath numeric,
		separate_shower numeric,
		separate_toilet numeric,
		lift numeric,
		swimming_pool numeric,
		air_conditioning numeric,
		fire_place numeric,
		garage numeric,
		cellar numeric,
		show_house_num numeric,
		photos text,
		tenant integer,
		area integer,
		nr_of_bathrooms integer,
		contract_length integer,
		nr_of_rooms integer,
		nr_of_living_rooms integer,
		stats text,
		available numeric,
		insert_date numeric,
		type text,
		pt_quality text,
		ground_floor text,
		garden numeric,
		garden_loc text,
		garden_area integer,
		roof_terrass numeric,
		roof_terrass_loc text,
		roof_terrass_area integer,
		balcony numeric,
		balcony_loc numeric,
		balcony_area integer,
		floor_quality text,
		rent_included text	
	)
`
