package datastore

import (
	"github.com/Maksadbek/xmlroom/src/models"
	"time"
)

var testItem models.Item = models.Item{
	ID:                 "1",
	Street:             "teststreet",
	HouseNumber:        "1",
	HouseNumAdd:        "1",
	PostCode:           "1",
	City:               "1",
	SubArea:            "1",
	EstateOwner:        "testOwner",
	MinPrice:           models.NullInt(1),
	ProjectName:        "testProjectName",
	HouseTypeInProject: "testHouseType",
	DescriptionNL:      "nl_description",
	DescriptionFR:      "fr_desctiption",
	DescriptionEN:      "en_description",
	DescriptionDE:      "de_description",
	DescriptionES:      "es_description",
	DescriptionIT:      "it_description",
	BrochureURL:        "testBrochureUrl",
	PlanURL:            "testPlanURL",
	BuildYear:          "testBuildYear",
	Furnished:          true,
	HidePrice:          true,
	UpdatePhotos:       true,
	Parking:            true,
	Bath:               true,
	SeparateShower:     true,
	SeparateToilet:     true,
	Lift:               true,
	SwimmingPool:       true,
	AirConditioning:    true,
	FirePlace:          true,
	Garage:             true,
	Cellar:             true,
	ShowHouseNum:       true,
	Photos:             []string{"test_1", "test_2"},
	Tenant:             models.NullInt(1),
	Area:               models.NullInt(1),
	NrOfBathrooms:      models.NullInt(1),
	ContractLength:     models.NullInt(1),
	MinContractLength:  models.NullInt(1),
	NrOfRooms:          models.NullInt(1),
	NrOfLivingRooms:    models.NullInt(1),
	Stats:              models.Period("testStats"),
	Available:          models.Date(time.Now()),
	InsertDate:         models.Date(time.Now()),
	Type:               models.HouseType("1"),
	PTQuality:          models.PTQuality("0"),
	GroundFloor:        models.Preference("3"),
	Garden:             true,
	GardenLoc:          models.Loc("ZW"),
	GardenArea:         models.NullInt(1),
	RoofTerrass:        true,
	RoofTerrassLoc:     models.Loc("O"),
	RoofTerrassArea:    1,
	Balcony:            true,
	BalconyLoc:         models.Loc(""),
	BalconyArea:        models.NullInt(1),
	FloorQuality:       models.FQuality("00000001"),
	RentIncluded:       models.RentStatus("111111"),
}

var testMembers []models.Member = []models.Member{
	models.Member{
		Items:         []models.Item{testItem},
		EstateAgentID: 123,
	},
}
